"""Ссылка на применённую акцию в позиции заказа — для статистики акций.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 14:01:35.226650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('applied_promotion_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_order_items_applied_promotion_id'), 'order_items', ['applied_promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_applied_promotion_id'), table_name='order_items')
    op.drop_column('order_items', 'applied_promotion_id')
    # ### end Alembic commands ###
