import type { Schemas } from "@/lib/api/client";

export function adminOrder(overrides: Partial<Schemas["AdminOrderOut"]> = {}): Schemas["AdminOrderOut"] {
  return {
    id: "o1",
    number: "NSB-10001",
    status: "paid",
    status_label: "Оплачен (новый)",
    created_at: "2026-10-05T09:00:00Z",
    paid_at: "2026-10-05T09:02:00Z",
    reserved_until: null,
    name: "Аня",
    phone: "+79001234567",
    email: "anya@example.ru",
    customer: { id: "c1", name: "Аня", email: "anya@example.ru", phone: "+79001234567", orders_count: 3, points_balance: 120 },
    payment_method: "online",
    items: [
      {
        id: "i1",
        product_id: "p1",
        name: "Да Хун Пао",
        product_type: "tea",
        variant_label: "50 г",
        grams: 50,
        qty: 2,
        unit_price_kop: 140_000,
        line_total_kop: 280_000,
        product_discount_kop: 0,
        order_discount_kop: 0,
        points_kop: 0,
        receipt_amount_kop: 280_000,
        promotion: null,
      },
    ],
    items_total_kop: 280_000,
    product_discount_kop: 0,
    order_discount_kop: 0,
    order_discount_source: null,
    promo_code: null,
    points_spent: 0,
    points_to_earn: 140,
    points_earned: 0,
    delivery_method: "cdek_pvz",
    delivery_label: "СДЭК — пункт выдачи",
    delivery_summary: "Москва, ПВЗ MSK1: Тверская, 1",
    delivery_data: {},
    delivery_kop: 35_000,
    total_kop: 315_000,
    refunded_kop: 0,
    refundable_kop: 315_000,
    tracking_number: null,
    tracking_url: null,
    customer_comment: "Позвоните заранее",
    internal_comment: null,
    discount_notes: [],
    history: [
      {
        from_status: null,
        to_status: "awaiting_payment",
        to_label: "Ожидает оплаты",
        actor_name: null,
        actor_type: "system",
        comment: null,
        created_at: "2026-10-05T09:00:00Z",
      },
    ],
    payments: [],
    refunds: [],
    next_steps: [{ to: "assembling", label: "Начать сборку", needs_tracking: false }],
    can_cancel: true,
    can_refund: true,
    ...overrides,
  };
}
